---
- name: Onboard new Ubuntu server
  hosts: all
  become: true
  vars:
    new_username: ansible
    new_password: "{{ 'joh3@121' | password_hash('sha512') }}"
  tasks:
    - name: Create new user
      ansible.builtin.user:
        name: "{{ new_username }}"
        password: "{{ new_password }}"
        shell: /bin/bash
        create_home: true

    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ new_username }}/.ssh"
        state: directory
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: '0700'

    - name: Add authorized key
      ansible.builtin.copy:
        src: "files/awx_id_rsa.pub"
        dest: "/home/{{ new_username }}/.ssh/authorized_keys"
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: '0600'
